### ISSUE TITLE
The app is not updated in f-droid

### ISSUE THREAD

**Issue by KOLANICH** [JohnMH/BoogDroid#18] opened 2017-11-12 17:22 UTC

**Comment by JohnMH** [comment] 2017-11-14 14:11
I know why: My name change. Ouch.

**Comment by holgersson32644** [comment] 2017-12-16 16:03
Any progress here? :-)

**Comment by albfan** [comment] 2017-12-16 16:19
@JohnMH if you grant me permissions I can update the app

**Comment by JohnMH** [comment] 2017-12-19 05:53
@albfan What do you need?

**Comment by albfan** [comment] 2017-12-19 07:59
Don't know is the process. Seems I need to open a request for packaging

https://gitlab.com/fdroid/rfp

But I suppose it should have a signature or similar to be accepted. Really don't know

**Comment by JohnMH** [comment] 2017-12-20 21:24
I'll just go and open an issue against the package that's already listed. The issue isn't that they don't have it packaged, it's that the code for updating was checking against a repo that no longer exists, at my old name.

**Comment by albfan** [comment] 2017-12-21 02:27
Can you link here an old issue with the last time you request for package?

**Comment by JohnMH** [comment] 2017-12-21 03:30
I don't remember doing that through their issue tracking, but if you wouldn't mind opening an issue against fdroiddata on their GitLab.com repo, I'd appreciate it.. Currently, I do not have access to my GitLab account.

**Comment by JohnMH** [comment] 2018-01-05 15:08
I have opened an issue against fdroiddata. Closing, follow up at https://gitlab.com/fdroid/fdroiddata/issues/1066 or reply here.

**Closed by JohnMH** 2018-01-05 15:08 UTC

**Comment by albfan** [comment] 2018-01-05 15:38
Better to see it at least one time from you

**Comment by IzzySoft** [comment] 2019-02-08 11:53
The issue at F-Droid is stuck, waiting for a new release here which includes the fix made (reverting the change of package ID). Any chance that will be done soon?

**Comment by bene64** [comment] 2021-07-05 07:04
We've just closed https://gitlab.com/fdroid/fdroiddata/-/issues/1066, as we can't do anything without a new tag here.

Please feel free to contact us, if the tag gets added.
